#!/usr/bin/env python3
"""Release lifecycle tool for the versioned RPC API reference.

The RPC reference is a separate Docusaurus docs instance (pluginId "api"):
  api-reference/            working dir  = Mainnet (current)
  api_versioned_docs/       placed snapshots (version-testnet, version-<release>)
  api_versioned_sidebars/   one sidebars json per snapshot
  api_versions.json         dropdown order below "current" (user-facing!)

Commands
  testnet  --zanod X --simplewallet Y --label L   regenerate the testnet snapshot
  archive  --name 2.2.1                           snapshot current mainnet as a release
  rollover --zanod X --simplewallet Y --label L   replace mainnet from a release binary
  check                                           validate invariants (CI-safe, no writes)

Rules encoded here (do not bypass):
  * generation goes to a temp dir first and is sanity-checked before replacing anything
  * rollover refuses to run unless an archive of the current content exists
  * hand-written files (the four intro pages, sidebars) are never overwritten by generation
  * api_versions.json is normalized to ["testnet", <archives newest-first>]
  * provenance (generator version stamp) must match the configured label

MUST STAY PYTHON 3.5 COMPATIBLE. The build machine that runs this on every
release build is Ubuntu 16.04 (python3 == 3.5.2). Do not introduce:
  * f-strings (3.6+)                     -> use "{}".format(...)
  * subprocess.run(capture_output=) (3.7+) -> use stdout=PIPE, stderr=PIPE
  * add_subparsers(required=) (3.7+)     -> set sub.required = True afterwards
  * reliance on dict literal ordering (3.7+) -> use OrderedDict where order is written out
A syntax error here fails the release build's doc step, not just the docs.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from collections import OrderedDict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORK = ROOT / "api-reference"
VDOCS = ROOT / "api_versioned_docs"
VSIDE = ROOT / "api_versioned_sidebars"
VJSON = ROOT / "api_versions.json"
CONFIG = ROOT / "docusaurus.config.js"
INTRO_PAGES = ["overview.md", "how-to-call-api.md", "daemon-rpc.md", "wallet-rpc.md"]
SIDEBAR_TEMPLATE = OrderedDict([
    ("apiSidebar", [
        OrderedDict([
            ("type", "link"),
            ("label", "← Build documentation"),
            ("href", "/docs/build/overview"),
        ]),
        OrderedDict([
            ("type", "autogenerated"),
            ("dirName", "."),
        ]),
    ]),
])


def die(msg):
    print("ERROR: {}".format(msg), file=sys.stderr)
    sys.exit(1)


def run_generator(binary, outdir):
    binary = Path(binary)
    if not binary.is_file():
        die("binary not found: {}".format(binary))
    subprocess.run(
        [str(binary), "--generate-rpc-autodoc={}".format(outdir)],
        check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=300,
    )
    pages = list(Path(outdir).glob("*.md"))
    if len(pages) < 40:
        die("{} generated only {} pages — sanity check failed".format(binary.name, len(pages)))
    return pages


def stamp_of(md_dir):
    for f in sorted(Path(md_dir).glob("*.md")):
        m = re.search(r"Auto-doc built with: (\S+)</sub>", f.read_text(encoding="utf-8"))
        if m:
            return m.group(1)
    return None


def generate_pair(zanod, simplewallet):
    tmp = Path(tempfile.mkdtemp(prefix="api-gen-"))
    d, w = tmp / "daemon", tmp / "wallet"
    d.mkdir()
    w.mkdir()
    run_generator(zanod, d)
    run_generator(simplewallet, w)
    print("generated: {} daemon, {} wallet (stamp {}) -> {}".format(
        len(list(d.glob("*.md"))), len(list(w.glob("*.md"))), stamp_of(d), tmp))
    return d, w


def replace_generated(target_root, daemon_dir, wallet_dir):
    """Replace ONLY generated method pages; keep intros + category jsons."""
    for sub, src in (("daemon-rpc-api", daemon_dir), ("wallet-rpc-api", wallet_dir)):
        dst = target_root / sub
        cat = dst / "_category_.json"
        cat_backup = cat.read_text(encoding="utf-8") if cat.exists() else None
        for old in dst.glob("*.md"):
            old.unlink()
        for f in src.glob("*.md"):
            shutil.copy2(str(f), str(dst / f.name))
        if cat_backup is not None:
            cat.write_text(cat_backup, encoding="utf-8")


def set_config_label(version_key, label):
    t = CONFIG.read_text(encoding="utf-8")
    pattern = r'({}: \{{\n\s*label: ")[^"]*(")'.format(version_key)
    new, n = re.subn(pattern, r"\g<1>" + label + r"\g<2>", t, count=1)
    if n != 1:
        die("could not update label for version '{}' in docusaurus.config.js".format(version_key))
    CONFIG.write_text(new, encoding="utf-8")
    print("config: {} label -> {}".format(version_key, label))


def normalize_versions_json():
    versions = json.loads(VJSON.read_text(encoding="utf-8"))
    archives = sorted(
        [v for v in versions if v != "testnet"],
        key=lambda v: [int(x) for x in re.findall(r"\d+", v)],
        reverse=True,
    )
    ordered = (["testnet"] if "testnet" in versions else []) + archives
    VJSON.write_text(json.dumps(ordered) + "\n", encoding="utf-8")
    print("api_versions.json -> {}".format(ordered))


def add_provenance(overview_path, stamp, extra=""):
    t = overview_path.read_text(encoding="utf-8")
    t = re.sub(r":::info (Testnet API reference|Archived API reference)\n.*?\n:::\n", "", t, flags=re.S)
    note = (":::info {}\n".format(extra or "API reference") +
            "Generated from `{}` on {} by scripts/api_version.py.\n:::\n".format(
                stamp, date.today().isoformat()))
    lines = t.split("\n")
    for i, l in enumerate(lines):
        if l.startswith("# "):
            lines.insert(i + 1, "\n" + note)
            break
    overview_path.write_text("\n".join(lines), encoding="utf-8")


def cmd_testnet(args):
    d, w = generate_pair(args.zanod, args.simplewallet)
    target = VDOCS / "version-testnet"
    if not target.exists():
        die("version-testnet does not exist; create it once manually or restore from git")
    replace_generated(target, d, w)
    add_provenance(target / "overview.md", stamp_of(d), "Testnet API reference")
    set_config_label("testnet", args.label)
    normalize_versions_json()
    print("testnet snapshot refreshed — run `check`, build, and review the diff before committing")


def cmd_archive(args):
    name = args.name
    target = VDOCS / "version-{}".format(name)
    if target.exists():
        die("version-{} already exists".format(name))
    if subprocess.run(["git", "-C", str(ROOT), "diff", "--quiet", "--", "api-reference"]).returncode != 0:
        die("api-reference/ has uncommitted changes; archive from a clean, pinned state")
    shutil.copytree(str(WORK), str(target))
    (VSIDE / "version-{}-sidebars.json".format(name)).write_text(
        json.dumps(SIDEBAR_TEMPLATE, indent=2) + "\n", encoding="utf-8")
    add_provenance(target / "overview.md", stamp_of(WORK / "daemon-rpc-api"), "Archived API reference")
    versions = json.loads(VJSON.read_text(encoding="utf-8"))
    if name not in versions:
        versions.append(name)
        VJSON.write_text(json.dumps(versions) + "\n", encoding="utf-8")
    normalize_versions_json()
    print("archived current mainnet as version-{} "
          "(label/path/banner use Docusaurus defaults)".format(name))


def release_line(stamp):
    """'2.2.1.502[72b939e]' -> '2.2.1' (MAJOR.MINOR.PATCH identifies a release line)."""
    m = re.match(r"v?(\d+\.\d+\.\d+)", stamp or "")
    return m.group(1) if m else None


def cmd_rollover(args):
    d, w = generate_pair(args.zanod, args.simplewallet)
    old_line = release_line(stamp_of(WORK / "daemon-rpc-api"))
    new_line = release_line(stamp_of(d))
    if old_line and new_line and old_line != new_line:
        # crossing a release boundary: preserve the old release before replacing it
        if not (VDOCS / "version-{}".format(old_line)).exists():
            print("release boundary {} -> {}: auto-archiving {} first".format(
                old_line, new_line, old_line))

            class _A:
                name = old_line

            cmd_archive(_A)
    elif not any(p.name.startswith("version-") and p.name != "version-testnet" for p in VDOCS.iterdir()):
        die("no archive snapshot exists — run `archive` first (rollover refuses to destroy history)")
    replace_generated(WORK, d, w)
    for page in INTRO_PAGES:
        if not (WORK / page).exists():
            die("hand-written page {} missing after rollover — aborting, restore from git".format(page))
    set_config_label("current", args.label)
    print("mainnet rolled over — run `check`, build, review diff (expected delta only), then commit.")
    print("when the build bot commits later into docs/build/rpc-api/, verify it is a no-op vs api-reference/")


def cmd_check(_args):
    problems = []
    for page in INTRO_PAGES:
        if not (WORK / page).exists():
            problems.append("missing hand-written page: api-reference/{}".format(page))
    if (WORK / "_category_.json").exists():
        problems.append("vestigial api-reference/_category_.json present")
    versions = json.loads(VJSON.read_text(encoding="utf-8"))
    if versions and "testnet" in versions and versions[0] != "testnet":
        problems.append("api_versions.json order wrong (testnet must be first): {}".format(versions))
    for v in versions:
        if not (VDOCS / "version-{}".format(v)).is_dir():
            problems.append("version '{}' listed but api_versioned_docs/version-{} missing".format(v, v))
        if not (VSIDE / "version-{}-sidebars.json".format(v)).is_file():
            problems.append("sidebars json missing for version '{}'".format(v))
    cfg = CONFIG.read_text(encoding="utf-8")
    stamp = stamp_of(WORK / "daemon-rpc-api") or ""
    m = re.search(r'current: \{\n\s*label: "Mainnet \(([^)]+)\)"', cfg)
    if m and m.group(1) not in stamp:
        problems.append("current label '{}' does not match page stamp '{}'".format(m.group(1), stamp))
    if problems:
        print("CHECK FAILED:")
        for p in problems:
            print("  -", p)
        sys.exit(1)
    print("check OK: {} snapshot(s) {}, mainnet stamp {}".format(len(versions), versions, stamp))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")
    sub.required = True  # add_subparsers(required=) is 3.7+; this form works everywhere
    for name, fn, needs in (
        ("testnet", cmd_testnet, True),
        ("archive", cmd_archive, False),
        ("rollover", cmd_rollover, True),
        ("check", cmd_check, False),
    ):
        p = sub.add_parser(name)
        p.set_defaults(fn=fn)
        if needs:
            p.add_argument("--zanod", required=True)
            p.add_argument("--simplewallet", required=True)
            p.add_argument("--label", required=True)
        elif name == "archive":
            p.add_argument("--name", required=True, help="release name, e.g. 2.2.1")
    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
